version: '3'

networks:
  nest:
    external: true

services:

  nest-type:
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB_NAME: 'nest_type_db'
    volumes:
      - nest-type:/usr/app
    networks:
      - nest
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_type_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --bind-address=0.0.0.0,
      ]

    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nest

volumes:
  db-data:
  nest-type: